name: Shell Script Validation

on:
  push:
    branches: [ main, v2 ]
  pull_request:
    branches: [ main, v2 ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install BATS
      run: |
        git clone https://github.com/bats-core/bats-core.git
        cd bats-core
        sudo ./install.sh /usr

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck

    - name: Run shellcheck
      run: shellcheck install.sh

    - name: Run unit tests
      run: bats tests/unit/functions.bats

    - name: Run minimal tests
      run: bats tests/minimal_test.bats
